name: zloop

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  zloop:
    runs-on: ubuntu-24.04
    env:
      WORK_DIR: /mnt/zloop
      CORE_DIR: /mnt/zloop/cores
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Setup SSH
      run: |
        mkdir -p $HOME/.ssh
        echo "ConnectTimeout 5" >> $HOME/.ssh/config
        echo "StrictHostKeyChecking no" >> $HOME/.ssh/config
        echo "${{ secrets.AUTHORIZED_KEYS }}" >> $HOME/.ssh/authorized_keys
        echo "${{ secrets.SSH_KEY }}" > $HOME/.ssh/id_ed25519
        echo "${{ secrets.KNOWN_HOSTS }}" >> $HOME/.ssh/known_hosts
        chmod 600 $HOME/.ssh/id_ed25519
        R=`shuf -n 1 -i 10000-60000`
        echo "Port  $R"
        ssh -x -N -C -f -R $R:127.0.0.1:22 mcmilk@${{ secrets.SOME_HOST }}
    - name: Install dependencies
      run: |
        sudo apt-get purge -y snapd google-chrome-stable firefox
        ONLY_DEPS=1 .github/workflows/scripts/qemu-3-deps-vm.sh ubuntu24
    - name: Autogen.sh
      run: |
        sed -i '/DEBUG_CFLAGS="-Werror"/s/^/#/' config/zfs-build.m4
        ./autogen.sh
    - name: Configure
      run: |
        ./configure --prefix=/usr --enable-debug --enable-debuginfo \
           --enable-asan --enable-ubsan \
           --enable-debug-kmem --enable-debug-kmem-tracking
    - name: Make
      run: |
        make -j$(nproc)
    - name: Install
      run: |
        sudo make install
        sudo depmod
        sudo modprobe zfs
        echo "SLEEEEP"
        sleep 212121
    - name: Tests
      run: |
# remove default swapfile and /mnt
sudo swapoff -a
sudo umount -l /mnt
DISK="/dev/disk/cloud/azure_resource-part1"
sudo sed -e "s|^$DISK.*||g" -i /etc/fstab
sudo wipefs -aq $DISK
sudo systemctl daemon-reload

# partition the disk as needed
DISK="/dev/disk/cloud/azure_resource"
sudo sgdisk --zap-all $DISK
sudo sgdisk -p \
 -n 1:0:+16G -c 1:"swap" \
 -n 2:0:0    -c 2:"tests" \
$DISK
sync
sleep 1

# swap with same size as RAM (16GiB)
sudo mkswap $DISK-part1
sudo swapon $DISK-part1

# JBOD 2xdisk for OpenZFS storage (test vm's)
SSD1=""

        sudo truncate -s 256G /mnt/vdev
        sudo zpool create cipool -m $WORK_DIR -O compression=on -o autotrim=on $DISK-part2
        sudo /usr/share/zfs/zloop.sh -t 600 -I 6 -l -m 1 -c $CORE_DIR -f $WORK_DIR -- -T 120 -P 60
    - name: Prepare artifacts
      if: failure()
      run: |
        sudo chmod +r -R $WORK_DIR/
    - name: Ztest log
      if: failure()
      run: |
        grep -B10 -A1000 'ASSERT' $CORE_DIR/*/ztest.out || tail -n 1000 $CORE_DIR/*/ztest.out
    - name: Gdb log
      if: failure()
      run: |
        sed -n '/Backtraces (full)/q;p' $CORE_DIR/*/ztest.gdb
    - name: Zdb log
      if: failure()
      run: |
        cat $CORE_DIR/*/ztest.zdb
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Logs
        path: |
          /mnt/zloop/*/
          !/mnt/zloop/cores/*/vdev/
        if-no-files-found: ignore
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: Pool files
        path: |
          /mnt/zloop/cores/*/vdev/
        if-no-files-found: ignore
